<?php
$login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
$welcomeMessage = $block->getWelcome();
?>

<div class="header-container header-style-9">
	<div class="header-top clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 d-lg-block d-none action-left">
					<div class="top-left-content clearfix">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-left')->toHtml(); ?>
					</div>
				</div>

				<div class="col-lg-6 col-md-12 action-right">
					<?php echo $block->getChildHtml('cart-header'); ?>
					<?php echo $block->getChildHtml('currency-header'); ?> 
					<?php echo $block->getChildHtml('language-header'); ?>
					
				</div>
			</div>
		</div>
	</div>



	<div class="header-bottom ontop-element">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-xl-1 col-sm-3">
					<div class="logo">
						<?php echo $block->getChildHtml('logo_theme'); ?>
					</div>
				</div>
				<div class="col-xl-7 col-sm-1 col-2">
					<div class="header-navigation">
						<div class="desktop-navigation">
							<div class="row align-items-center">
								<div class="col-lg-3">
									<div class="vertical-megamenu">
										<?php
										if ($_config->getGeneral('menu_style') == 'megamenu') {
											echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vertical-megamenu')->toHtml();
										} else {
											echo $block->getChildHtml('navigation-header');
										} ?>
									</div>
								</div>

								<div class="col-lg-9">
									<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('horizontal-megamenu')->toHtml(); ?>
								</div>
							</div>
						</div>

						<div class="navigation-mobile-container">
							<?php echo $block->getChildHtml('navigation.mobile'); ?>
						</div>
					</div>
				</div>
				<div class="col-xl-4 col-sm-8 col-10">
					<div class="middle-right">
						<div class="middle-right-container">
							<?php echo $block->getChildHtml('search-header-pro'); ?>

							<div class="wishlist-header">
								<a href="<?php echo $this->getUrl('wishlist') ?>"
										   title="<?php echo __('My Wishlist') ?>">
									<span>
										<?php echo __('My Wishlist') ?>
									</span>
								</a>
							</div>
							<div class="header-account">
								<div class="drop-account" data-move="customer-mobile"> 
									<?php echo $this->getChildHtml("header.links"); ?>
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


