<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

$_config     = $this->helper('Sm\Autostore\Helper\Data');
$footerStyle = $_config->getThemeLayout('footer_style');
?>

<?php if ($footerStyle == "footer-1") { ?>
    <div class="footer-container footer-style-1">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-content')->toHtml(); ?>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-en-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php if ($footerStyle == "footer-2") { ?>
    <div class="footer-container footer-style-2">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>

                        <div class="col-lg-7">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php if ($footerStyle == "footer-3") { ?>
    <div class="footer-container footer-style-3">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-3-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php if ($footerStyle == "footer-4") { ?>
    <div class="footer-container footer-style-4">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-4-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php if ($footerStyle == "footer-5") { ?>
    <div class="footer-container footer-style-5">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-5-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="col-lg-5">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<?php if ($footerStyle == "footer-6") { ?>
    <div class="footer-container footer-style-6">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-6-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<?php if ($footerStyle == "footer-7") { ?>  
   <div class="footer-style-7">
    
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-7-content')->toHtml(); ?>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                        <div class="col-lg-6 payment-footer">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links')->toHtml(); ?>
                        </div>
                        <div class="col-lg-6">
                           <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>
                </div>
            </div>
        </div>
</div>
<?php } ?>
<?php if ($footerStyle == "footer-8") { ?>
    <div class="footer-container footer-style-8">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-8-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="content">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="col-lg-5">
                            <div class="footer-payment">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<?php if ($footerStyle == "footer-9") { ?>
    <div class="footer-container footer-style-9">
        <div class="footer-wrapper">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-9-content')->toHtml(); ?>

            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="copyright-footer">
                                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                                <?php } else { ?>
                                    <address><?php /* @escapeNotVerified */
                                        echo $block->getCopyright() ?></address>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="col-lg-6">
                             <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links')->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

